### ISSUE TITLE
CI 似乎没有工作

### ISSUE THREAD

**Issue by coconut49** [tuna/blogroll#113]
`https://tuna.github.io/blogroll/opml.xml` 的内容与 `https://github.com/tuna/blogroll/blob/master/README.md` 的内容不匹配。
`lextang.com` 这个 RSS 订阅源仍然存在于 `https://tuna.github.io/blogroll/opml.xml` 中，并且看起来变成了色情网站 :(
13天前新增的 `https://www.junz.org/index.xml` 也没有出现在 `https://tuna.github.io/blogroll/opml.xml` 中

**Comment by scateu** [comment]
travis-ci貌似有变  我对ci不熟，请 @CircuitCoder 出山帮忙看一哈

当前人肉ci了一下

**Comment by ZenithalHourlyRate** [comment]
CI 已经工作了。
