### ISSUE TITLE
[Help Wanted] 无法在免费版 Inoreader 中订阅合辑 OPML 

### ISSUE THREAD

**Issue by relishInertia** [tuna/blogroll#139]
在 Inoreader （免费版）中查找不到无法通过合辑 OPML 添加订阅源。
![Inoreader 无法添加订阅合辑](https://user-images.githubusercontent.com/60534959/220409477-4c612121-b87f-4fe8-8184-7ce4809dda44.png)

但是可以单独正常添加某一用户的 RSS。以 [Gee Law's Blog]([https://geelaw.blog/rss.xml
) 为例，在 Inoreader 中可添加其订阅源。
![Inoreader 单博客订阅可正常添加](https://user-images.githubusercontent.com/60534959/220407671-19de9526-3712-43b3-9064-be9fe84f8253.png)

此外，我去 Feedly 试了下，是可以探查到博客订阅源的，但是是以单个添加的形式罗列。请问是否有批量添加订阅的方式，请告知与我，不胜感激。我试着以“Feedly 批量添加订阅”作为关键词在谷歌和必应搜索，但没找到相关信息。或许我遗漏了，毕竟大晚上的犯困=o-

**Comment by xuruizhi** [comment]
在偏好设置这里：
![image](https://github.com/tuna/blogroll/assets/22674728/3d86788a-c760-46b7-851e-a3be3689a63d)

![image](https://github.com/tuna/blogroll/assets/22674728/ca5db625-8db5-4fda-9246-29c63da08548)

![image](https://github.com/tuna/blogroll/assets/22674728/e261652e-b644-46a2-b205-bd58fde0ee0f)
