### ISSUE TITLE
建议给每个 blog 加一些 tag

### ISSUE THREAD

**Issue by forrestchang** [tuna/blogroll#18]
可以根据博客的主要写的内容，例如 `前端`，`后端`，`Python`，`Java` 等。

**Comment by huiyiqun** [comment]
一般 blog 里每篇文章都有 tag，可以全部订阅然后根据 tag 来 filter。

**Comment by forrestchang** [comment]
@huiyiqun 并不是每个博客都想订阅的，增加 tag 可以方便前期筛选。

**Comment by scateu** [comment]
我理解你的意思。但我的想法是这样的: 搞"前端"的人有时候也要看看搞"后端"的人在做些啥，搞"Python"的人，也需要看看搞"Java"的人在干些啥，这样才能起到互通有无的作用嘛不是~

另外，其实这些独立blog的更新频率一般不会太高，比如一两个月一篇，而在RSS阅读器里看到不对口味的，可以Mark All as Read，或者单独unsubscribe

（主要是我自己的blog根本没有办法被分类... 既不前端也不后端既不Python也不Java.... =. =
