### ISSUE TITLE
add

### ISSUE THREAD

**Issue by hzj991** [tuna/blogroll#43]
https://hzj991.github.io/

**Comment by scateu** [comment]
@hzj991 木有找到你的rss地址啊

**Comment by Harry-Chen** [comment]
@hzj991 看到你用的是 hexo，可以用 https://github.com/hexojs/hexo-generator-feed 这个插件来生成 RSS 页面。有了 RSS 以后，请直接编辑文件并向我们发送 pull request，不用提 issue 了。
