### ISSUE TITLE
部分博客不可用

### ISSUE THREAD

**Issue by somewheve** [tuna/blogroll#55]
推荐定期维护  
筛选与删除部分博客地址

**Comment by scateu** [comment]
我也遇到过几个，不过有一些博客只是访问问题，隔天就又能用了...

你遇到的是哪几个？

**Comment by somewheve** [comment]
大概就几个 你写个爬虫程序挨个访问一遍  维护一个列表呗

**Comment by scateu** [comment]
好！ 我谋划一下
