### ISSUE TITLE
什麼是"周围同学"？

### ISSUE THREAD

**Issue by zaoqi** [tuna/blogroll#59]

**Comment by scateu** [comment]
定义为信息可达?

**Comment by zaoqi** [comment]
@scateu
所有能看到https://github.com/tuna/blogroll的人？

**Comment by dotkrnl** [comment]
我的理解是身份认同包含 TUNA 的人，比如别人问「你知道 TUNA 吗」的时候至少会回答「emmm 我应该可能或许算 TUNA 成员的吧」 😂

**Comment by zaoqi** [comment]
@dotkrnl 

TUNA似乎有一個明確的加入程序

```
如果你是清华学生

除了订阅邮件列表，请再在 校团委社团部平台 点击 "我要加入" 加入协会。
```

**Comment by dotkrnl** [comment]
如果不是清华学生，就基本上靠身份认同（
