### ISSUE TITLE
请求添加一个其他博客列表的repo到readme上

### ISSUE THREAD

**Issue by LasGoneN0** [tuna/blogroll#75]
https://github.com/timqian/chinese-independent-blogs

或是交pull request合并一下也可以

**Comment by scateu** [comment]
我觉得还是慢慢一个一个item自发迁移比较好。刚看了一下这个列表的前几个条目似乎都是微信公众号和微博大V

**Comment by scateu** [comment]
我把它加到See Also里好了～
