### ISSUE TITLE
萌新求加~

### ISSUE THREAD

**Issue by GeeLaw** [tuna/blogroll#8]
| Name | RSS | HTML |
| --- | --- | --- |
| Gee Law’s Blog | https://geelaw.blog/rss.xml | https://geelaw.blog/ |

提示：不要把 `’` 改成 `'`；RSS 只有 hero image 和 abstract，没有全文；为了正确的排版，不建议使用可以抓取全文输出 RSS 的工具，也不建议使用 Reading view 或者类似功能。

**Comment by scateu** [comment]
刚准备怒斥一番你要求真多... 但点了进去发现你的博客排版是真漂亮啊~  赞一个

**Comment by scateu** [comment]
done
