### ISSUE TITLE
http://capbone.com/

### ISSUE THREAD

**Issue by mr-shitou** [tuna/blogroll#87]
同学，我就点了一个，这是被盗号了么，点进去吓我一跳。这个列表看来不能只添加，还要有删除功能

**Comment by xavieryao** [comment]
感谢！

**Comment by scateu** [comment]
http://archive.is/LNAYY  看来是域名到期了 //sad

感谢反馈～

**Comment by mr-shitou** [comment]
哈哈，客气啦，要感谢你们的开源和维护
